---
- name: Testing andrewrothstein.step
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'step --version'
      ansible.builtin.command: /usr/local/bin/step --version
      changed_when: false
      register: step_test_output
    - name: Output from 'step --version'
      ansible.builtin.debug:
        msg: '{{ step_test_output.stdout }}'
