---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install in {{ step_install_dir }}
  become: yes
  stat:
    path: '{{ step_install_dir }}'
  changed_when: False
  register: step_binary
- when: not step_binary.stat.exists
  block:
    - name: downloading {{ step_url }}
      become: yes
      become_user: root
      get_url:
        url: '{{ step_url }}'
        dest: '{{ step_tmp_tgz }}'
        checksum: '{{ step_checksum }}'
        mode: 0644
    - name: unarchive {{ step_tmp_tgz }} to {{ step_parent_install_dir }}
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: '{{ step_tmp_tgz }}'
        dest: '{{ step_parent_install_dir }}'
        creates: '{{ step_install_exe }}'
  always:
    - name: rm {{ step_tmp_tgz }}
      become: yes
      become_user: root
      file:
        path: '{{ step_tmp_tgz }}'
        state: absent
- name: linking {{ step_install_link }} to {{ step_install_exe }}
  become: yes
  become_user: root
  file:
    src: '{{ step_install_exe }}'
    dest: '{{ step_install_link }}'
    state: link
