---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install in {{ step_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ step_install_dir }}'
  changed_when: false
  register: step_binary
- name: Downloading and installing step
  when: not step_binary.stat.exists
  block:
    - name: Downloading {{ step_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ step_url }}'
        dest: '{{ step_tmp_tgz }}'
        checksum: '{{ step_checksum }}'
        mode: '644'
    - name: Unarchive {{ step_tmp_tgz }} to {{ step_parent_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ step_tmp_tgz }}'
        dest: '{{ step_parent_install_dir }}'
        creates: '{{ step_install_exe }}'
  always:
    - name: Rm {{ step_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ step_tmp_tgz }}'
        state: absent
- name: Linking {{ step_install_link }} to {{ step_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ step_install_exe }}'
    dest: '{{ step_install_link }}'
    state: link
